version: '2'

services:
  redis:
    image: redis:latest
    container_name: sentry_redis
    networks: 
      - sentry

  postgres:
    image: postgres:latest
    container_name: sentry_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
     - /home/service/pgdb:/var/lib/postgresql/data
    networks: 
      - sentry
  sentry:
    image: sentry:latest
    container_name: sentry
    links:
     - redis
     - postgres
    volumes:
     - /home/service/sentrydata:/var/lib/sentry/file
     - ./conf:/etc/sentry
    ports:
      - 80:9000
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: ${SENTRY_POSTGRES_HOST}
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_REDIS_HOST: ${SENTRY_REDIS_HOST}
      SENTRY_ADMIN_USERNAME: ${SENTRY_ADMIN_USERNAME}
      SENTRY_ADMIN_PASSWORD: ${SENTRY_ADMIN_PASSWORD}
      SENTRY_ADMIN_EMAIL: ${SENTRY_ADMIN_EMAIL}
    networks:
      - sentry

  cron:
    image: sentry:latest
    container_name: sentry_cron
    links:
     - redis
     - postgres
    volumes:
     - ./conf:/etc/sentry
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: ${SENTRY_POSTGRES_HOST}
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_REDIS_HOST: ${SENTRY_REDIS_HOST}
      SENTRY_ADMIN_USERNAME: ${SENTRY_ADMIN_USERNAME}
      SENTRY_ADMIN_PASSWORD: ${SENTRY_ADMIN_PASSWORD}
      SENTRY_ADMIN_EMAIL: ${SENTRY_ADMIN_EMAIL}
    networks: 
      - sentry

  worker:
    image: sentry:latest
    container_name: sentry_worker
    links:
     - redis
     - postgres
    command: "sentry run worker"
    volumes:
     - ./conf:/etc/sentry
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: ${SENTRY_POSTGRES_HOST}
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_REDIS_HOST: ${SENTRY_REDIS_HOST}
      SENTRY_ADMIN_USERNAME: ${SENTRY_ADMIN_USERNAME}
      SENTRY_ADMIN_PASSWORD: ${SENTRY_ADMIN_PASSWORD}
      SENTRY_ADMIN_EMAIL: ${SENTRY_ADMIN_EMAIL}
    networks:
      - sentry
networks:
  sentry:
    external: true
